apiGateway:
  replicaCount: 1
  image:
    repository: rookiesdogun/api-gateway
    tag: test
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  spring:
    profiles: local
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"


  ingress:
    ingressClassName: nginx
    path: /
    pathType: Prefix
    port:
      http: 80
      https: 443
    tls: false
