apiPayment:
  replicaCount: 1
  image:
    registry: rookiesdogun
    repository: api-payment
    tag: v20250808081026
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  database:
    host: api-payment-database-service
    port: 3306
    name: payment
    username: rookies
    password: rookies
